// <auto-generated />
namespace FMIRatingsAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDisciplinesAndTutors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDisciplinesAndTutors));
        
        string IMigrationMetadata.Id
        {
            get { return "201412091058169_AddDisciplinesAndTutors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
