// <auto-generated />
namespace FMIRatingsAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDisciplineNameAndCompositeKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDisciplineNameAndCompositeKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201412091115289_AddDisciplineNameAndCompositeKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
